busca entre rango de fechas
NisumCL/proyecto_calendario pull request #11
Opened 2022-02-08 14:34 UTC by javierast23

Esta es la rama elegida por todas.

2022-02-08 15:23 UTC, aursog requested changes
Algunos comments menores

2022-02-08 15:23 UTC, aursog commented on app.js
> +// function validarFechaMayor(fecha1, fecha2){
Sacar código commented-out

2022-02-08 15:23 UTC, aursog commented on app.js
> +function formatoFechas(date){
isValidDate mejor que formatoFechas

2022-02-08 15:23 UTC, aursog commented on app.js
> +if (formatoFechas(fechaInicio) && formatoFechas(fechaFin)) {
Qué pasa si solo una de las fechas cumple el formato y la otra no?. No sería mejor tener un mensaje diferenciado, para seguir el error más fácil?.

2022-02-08 16:00 UTC, KiraElric commented on app.js
> +function formatoFechas(date){
Se refiere a cambiar el nombre de la función?

2022-02-08 16:01 UTC, KiraElric commented on app.js
> +if (formatoFechas(fechaInicio) && formatoFechas(fechaFin)) {
Eso, es parte de los Test a realizar como siguiente tarea.

2022-02-08 17:05 UTC, FranciscaLjubetic commented on app.js
> +function formatoFechas(date){
> isValidDate mejor que formatoFechas

Si se trata del nombre, nos podrías dar más recomendaciones de nombres de funciones?

2022-02-08 17:18 UTC, aursog commented on app.js
> +function formatoFechas(date){
Si, la idea es que esta función sea autoexplicativa. El nombre <code>formatoFechas</code> no me explica que hace la función. 

En cambio si consideramos como nombre de la función <code>isValidDate</code> o <code>isValidFormatDate</code> automáticamente podremos saber que hace la función (independientemente de su implementación).

2022-02-08 17:26 UTC, aursog requested changes

2022-02-08 17:26 UTC, aursog commented on app.js
> +    if (dateOk) {
```suggestion
    return dateOk
```

2022-02-08 17:26 UTC, aursog commented on app.js
> +    if (dateOk) {
Acá la idea es sacar el if (agrega complejidad ciclomática y la variable dateOk es suficiente para resolver).

Otra opción, pero es menos verbosa

```suggestion
   return regex.text(date)
```

O hacerlo en una función de una sola linea tipo

```suggestion
const isValidDate = (date) => ....
```

2022-02-08 17:26 UTC, aursog commented on app.js
> +if (isValidDate(fechaInicio) && isValidDate(fechaFin)) {
```suggestion
if (isValidDate(fechaInicio) && isValidDate(fechaFin) {
//
} else if(!isValidDate(fechaInicio)) {
  // fecha inicio inválida
} else if (!isValidDate(fechaFin)) {
  // fecha fin inválida
}
```

2022-02-10 03:26 UTC, aursog approved these changes
LGTM... Good Job Girls

2022-02-10 03:26 UTC, merged