Creación de rutas GET para el mes actual y el siguiente mes
NisumCL/proyecto_calendario pull request #23
Opened 2022-02-25 00:27 UTC by KiraElric

Extraccion de servicios para rutas de consulta para obtener los cumpleaños del mes actual y el mes siguiente.

2022-02-28 18:39 UTC, FranciscaLjubetic requested changes

2022-02-28 18:39 UTC, FranciscaLjubetic commented on src/utils/validator.js
>    const dateOk = regex.test(date);
Estimadas, a la fecha hay que cambiarle los slashs por guiones.

2022-02-28 22:04 UTC, melamito commented on src/app.js
> +    res.send({ error: 'Problems with startDate' });
Reparado en el pull request 27 
https://github.com/NisumCL/proyecto_calendario/pull/27

2022-03-01 14:54 UTC, aursog requested changes
Buen trabajo, solo un comentario menor

2022-03-01 14:54 UTC, aursog commented on src/utils/reader.js
> +      throw new Error(err);
Tienen el <code>throw</code> pero no veo el manejo de la exception en la respuesta. 
Debería haber algún bloque <code>try-catch</code> en donde modifiquemos la respuesta del servidor según el error presentado en la fuente de datos.

2022-03-02 14:29 UTC, aursog approved these changes

2022-03-15 02:43 UTC, aursog approved these changes

2022-03-15 02:43 UTC, merged