Belopez front
NisumCL/proyecto_calendario pull request #25
Opened 2022-02-28 19:55 UTC by Be-ri-lo

Creación de Vistas:  Formulario y Mes siguiente. Y construcción de la Tabla con el listado de los resultados.

2022-03-02 13:23 UTC, KiraElric commented on public/js/script.js
> +  fetch(url).then(response => {
Aqui pasaria lo mismo que en el archivo anterior, el fetch de la linea 44 estaria loggeando el resultado en el servicio de la consola, mientras que el fetch de la fila 18 seria el que estaria poblando la tabla con el resultado.

2022-03-02 13:25 UTC, KiraElric commented on public/js/script.js
> +  async function loadIntoTable(url) {
Vi que esta función es exactamente igual a la que se encuentra en el archivo next_month, entonces no seria mejor tomar esta funcion dejarla en otro archivo como utils y exportarla para ser usada en este archivo y en el de next_month, para asi no tener que escribirla por duplicado?

2022-03-02 13:39 UTC, melamito requested changes

2022-03-02 18:15 UTC, Be-ri-lo reviewed
Se realizan cambios solicitados, queda sólo uno pendiente por problemas de importación, se solicitará ayuda.

2022-03-02 18:15 UTC, Be-ri-lo commented on public/js/next-month.js
> +  for (let i = 0; i < cols.length; i++) {
ok!. Se realiza cambio de for a forEach.

2022-03-02 18:15 UTC, Be-ri-lo commented on public/js/next-month.js
> +  for (let i = 0; i < birthdays.length; i++) {
Cambio ok!

2022-03-02 18:15 UTC, Be-ri-lo commented on public/js/script.js
> +  async function loadIntoTable(url) {
Se intenta encapsular y agrupar funciones, al importar la función al archivo donde se utilizará esta, se genera el siguiente error: "Client on Node.js: Uncaught ReferenceError: require is not defined"
Se investiga y prueba de distintas formas, pero no se consigue resolver la falla. Entonces, quedan dos archivos js, uno para cada vista repitiendo la función.  Por lo mismo queda aún pendiente resolver la solicitud.

2022-03-02 18:15 UTC, Be-ri-lo commented on public/js/script.js
> +  fetch(url).then(response => {
Ok!, eliminé segundo fetch, solo dejando uno

2022-03-02 19:03 UTC, Be-ri-lo commented on src/read.js
> +// module.exports = { readData: readData };
Archivo fue eliminado

2022-03-02 19:03 UTC, Be-ri-lo commented on Pruebas/ramas_anteriores.js
> +        );
Archivo eliminado

2022-03-02 19:04 UTC, Be-ri-lo commented on src/show.js
> +// };
Archivo eliminado

2022-03-02 19:04 UTC, Be-ri-lo commented on src/test.js
> +};
Archivo eliminado

2022-03-02 19:11 UTC, KiraElric commented
Beatriz, logre arreglar lo de la fecha en el archivo csv, pero no se porque agrega una fila adicional al final del archivo

2022-03-02 21:44 UTC, melamito approved these changes

2022-03-04 14:46 UTC, Be-ri-lo commented on public/js/script.js
> +  async function loadIntoTable(url) {
Se corrige error

2022-03-04 14:50 UTC, KiraElric commented on Pruebas/ramas_anteriores.js
> +const fs = require("fs");
Bea, volvio a aparecer este archivo en el push. Este se seguira usando o lo deberiamos eliminar?

2022-03-04 14:50 UTC, KiraElric commented on mails_y_cumples_03.csv
> +"ABREU, CESAR",cabreu@nisum.com,1985-02-15,Nisum Latam
Aqui es el cambio de fecha en el cumpleaños de esta persona.

2022-03-04 14:53 UTC, Be-ri-lo commented on Pruebas/ramas_anteriores.js
> +const fs = require("fs");
Ok, lo elimino. :/

2022-03-04 14:55 UTC, KiraElric commented on Pruebas/ramas_anteriores.js
> +const fs = require("fs");
Si, no entendi porque aparecio de nuevo :(

2022-03-04 14:59 UTC, KiraElric commented on public/js/form.js
> +}
Aqui es más una consulta, ¿no es necesario llamar la función al final del archivo? Porque veo que esta definida, pero ¿dónde se esta llamando para que se ejecute? ¿o no es necesario para que esta funcione?

2022-03-15 02:51 UTC, aursog requested changes

2022-03-15 02:51 UTC, aursog commented on src/utils/service.js
> +const fileInfo = dataFile('./mails_y_cumples_03.csv');
@Be-ri-lo por que eliminamos la función acá?

2022-03-15 02:51 UTC, aursog commented on src/app.js
> +const publicDirectoryPath = path.join(__dirname, '../public');
mover a un file llamado config.js

2022-03-15 02:51 UTC, aursog commented on src/app.js
> +app.get('/form', (req, res) => {
Yo separaría las rutas del front y del back en dos files distintos

2022-03-15 02:51 UTC, aursog commented on public/js/next-month.js
> +function nextMonth() {
cuál es la idea de esto?

2022-03-16 15:20 UTC, closed without merging